config/routes.rb
Trinlist::Application.routes.draw do
  get 'categories/:category' => 'items#index', as: :category
  devise_for :users
  resources :pages
  resources :items, except: :edit
  get '/listings' => 'items#my_listings'
  get '/listings/edit/:id' => 'items#edit'

  root :to => "items#index"

  

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates_presence_of :name, :description, :location, :price
	validates_length_of :name, :maximum => 120
	validates_numericality_of :price, :greater_than_or_equal_to => 0
	validate :between_one_and_three_categories?

	belongs_to :user
	acts_as_taggable
	acts_as_taggable_on :categories

	has_attached_file :image, 
		:styles => { :resized => "250x250>", :original => "600x600>" },
		:storage => :s3,
    :bucket => ENV['AWS_BUCKET'],
    :path => ":attachment/:id/:style.:extension",
    :url => ":s3_domain_url",
    :s3_credentials => {
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    }
	validates_attachment_content_type :image, :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'],
		:message => "must be a jpeg, gif or png file."
	validates_attachment_size :image, :less_than => 7.megabytes

	def between_one_and_three_categories?
		if ((self.category_list.length == 0) || (self.category_list.length > 3))
			errors.add(:base, "You must choose between one and three categories")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :items
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	after_filter :store_location

	def store_location
	 # store last url - this is needed for post-login redirect to whatever the user last visited.
	    if (request.fullpath != "/users/sign_in" && \
	        request.fullpath != "/users/sign_up" && \
	        request.fullpath != "/users/password" && \
	        !request.xhr?) # don't store ajax calls
	      session[:previous_url] = request.fullpath 
	    end
	end

	def after_sign_in_path_for(resource)
	  request.env['omniauth.origin'] || stored_location_for(resource) || root_path
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_filter :authenticate_user!, :only => [:new, :edit]

	def index
		if (params[:category] == "free")
			@items = Item.where("price = 0").order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
		elsif params[:category]
			@items = Item.tagged_with(params[:category], :order => "created_at DESC").paginate(:page => params[:page], :per_page => 15)
		else
			@items = Item.tagged_with("books", :order => "created_at DESC").paginate(:page => params[:page], :per_page => 15).order("created_at DESC")
		end
	end

	def show
		@item = Item.find(params[:id])
		@seller = User.find(@item.user_id)
		@coop = User.find(22)
	end

	def my_listings
		@items = Item.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15).order("created_at DESC")
	end

	def edit
		@item = Item.find(params[:id])
		unless (@item.user == current_user)
			flash[:alert] = "You don't have access there"
			redirect_to root_path
		end
	end

	def update
	  @item = Item.find(params[:id])
	  @item.category_list = params[:categories]
	 
	  if @item.update(item_params)
	  	flash[:notice] = "Your listing has been updated"
	    redirect_to @item
	  else
	    render 'edit'
	  end
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@item.user = current_user
		@item.category_list = params[:categories]

		if @item.save
			flash[:notice] = "Your listing has been posted."
			redirect_to root_path
		else
			render "new"
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		respond_to do |format| 
			format.html { redirect_to listings_path } 
			format.xml { head :ok } 
		end
  	end

  	private
		def item_params
			params.require(:item).permit(:name, :description, :location, :price, :image)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/create.html.erb
<h2>create</h2>

app/views/items/edit.html.erb
<div id="edit_wrapper" class="container">
  <% provide(:title, "Edit listing") %>

  <%= link_to "← Back", :back %>

  <h1>Edit your listing</h1>

  <%= form_for(@item, :html => {:class=> "form-signin"}) do |f| %>

    <div><%= f.label :name %><br />
    <%= f.text_field :name, :class=> "form-control" %></div>

    <div><%= f.label :description %><br />
    <%= f.text_area :description, :class=> "form-control" %></div>

    <div class="row">
      <div class="col-md-9 col-xs-8">
        <div class="field">
          <label for="item_location">Location</label><br />
          <%= f.text_field :location, :class=> "form-control" %>
        </div>
      </div>
      <div class="col-md-3 col-xs-4">
        <label for="item_price">Price</label><br />
        <div id="price_wrapper" class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.text_field :price, :class=>"form-control" %>
        </div>
      </div>
    </div>

    <div id="categories_wrapper" class="field">
      <%= f.label :categories %><br />
      <%= check_box_tag 'categories[]', 'furniture', @item.category_list.include?("furniture") ? true : false %>
      <%= label_tag(:furniture) %>
      <%= check_box_tag 'categories[]', 'electronics', @item.category_list.include?("electronics") ? true : false %>
      <%= label_tag(:electronics) %>
      <%= check_box_tag 'categories[]', 'clothes', @item.category_list.include?("clothes") ? true : false %>
      <%= label_tag(:clothes) %>
      <%= check_box_tag 'categories[]', 'books', @item.category_list.include?("books") ? true : false %>
      <%= label_tag(:books) %>
      <%= check_box_tag 'categories[]', 'misc', @item.category_list.include?("misc") ? true : false %>
      <%= label_tag(:misc) %>
    </div>

    <%=link_to "Delete this listing", item_path(@item), :method => :delete, :confirm => "Are you sure you want to delete this listing?" %>

    <div><%= f.submit "Save changes", :id => "submit_button", :class => "btn btn-lg btn-primary btn-block" %></div>
  <% end %>
</div>

app/views/items/index.html.erb
<% if @items.count > 0 %>
	<div id="content_wrapper">
		<div id="pagination_top" class="digg_pagination">
			<%= will_paginate @items %>
		</div>
		<table id="main_table" class="table">
			<thead>
				<tr>
					<th>Listing</th>
					<th>Price</th>
					<th>Location</th>
					<th>Time</th>
				</tr>
			</thead>
			<% @items.each do |item| %>
				<tr class="list_item" url="/items/<%= item.id %>">
					<td class="name_td"><% if current_user == item.user %><span class="current_user_listing">• </span><% end %><%= item.name %></td>
					<td>
						<% if item.price == 0 %>
							Free
						<% else %>
							<%= number_to_currency(item.price) %>
						<% end %>
					</td>
					<td>
						<% if current_user.present? %>
							<%= item.location %>
						<% else %>
							<% location = item.location.try(:split, '') || 'something'.split('') %>
							<% location.map! {|c| "█"} %><%= location.join %>
						<% end %>
					</td>
					<td id="time_td"><%= time_ago_in_words(item.created_at).gsub('about','') %> ago</td>				</tr>
			<% end %>
		</table>
		<div class="digg_pagination">
			<%= will_paginate @items %>
		</div>
	</div>

<% else %>
	<div id="gold_alert" class="alert alert-success">No listings have been posted in this category yet. <%= link_to 'Add one yourself!', new_item_path %></div>
<% end %>

app/views/items/my_listings.html.erb
<div id="my_listings_content_wrapper">
	<% if current_user.items.any? %>
		<h2>My Listings</h2>
		<table id="my_listings_table" class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<% @items.each do |item| %>
				<tr>
					<td><%= item.name %></td>
					<td>
						<%= link_to 'View', item %> | 
						<%= link_to 'Edit', {:controller => 'items', :action => 'edit', :id => item.id} %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	<% else %>
		You haven't posted any listings yet. <%= link_to 'Post one now!', new_item_path %>
	<% end %>
</div>

app/views/items/new.html.erb
<% if @item.errors.any? %>
  <div id="red_alert" class="alert alert-danger center_text">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li class="no_bullet"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="listing_wrapper" class="container">
  <h2>New Listing</h2>
  Listings automatically expire after 15 days. Give your listing a price of $0 to add it to the "free" category.<br><br>

   <%= form_for(@item) do |f| %>

   <div class="field">
      <%= f.label :title %>*<br />
      <%= f.text_field :name, :class => "form-control" %>
    </div>

    <div class="field">
      <%= f.label :description %>*<br />
      <%= f.text_area :description, :class => "form-control" %>
    </div>

    <div class="row">
      <div class="col-md-9 col-xs-8">
        <div class="field">
          <label for="item_location">Location</label>*<br />
          <%= f.text_field :location, :class => "form-control", :id => "item_location", :placeholder => "e.g. Hansen, Jarvis, Crescent St." %>
        </div>
      </div>
      <div class="col-md-3 col-xs-4">
        <label for="item_price">Price</label>*<br />
        <div id="price_wrapper" class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.text_field :price, :class => "form-control", :id => "item_price", :placeholder => "0.00" %>
        </div>
      </div>
    </div>

    <div class="image_upload_button">
      <%= f.label "Add image" %> (optional)
      <%= f.file_field :image, :class => "" %>
    </div>

    <div id="categories_wrapper" class="field">
      <%= f.label :categories %>*<br />
      <%= check_box_tag 'categories[]', 'furniture' %>
      <%= label_tag(:furniture) %>
      <%= check_box_tag 'categories[]', 'electronics' %>
      <%= label_tag(:electronics) %>
      <%= check_box_tag 'categories[]', 'clothes' %>
      <%= label_tag(:clothes) %>
      <%= check_box_tag 'categories[]', 'books' %>
      <%= label_tag(:books) %>
      <%= check_box_tag 'categories[]', 'misc' %>
      <%= label_tag(:misc) %>
    </div>

    <div class="actions">
      <%= f.submit "Add your listing!", :id => "submit_button", :class => "btn btn-lg btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div id="show_listing_wrapper" class="container">
	<%= link_to "← Back", :back %>
	<% if current_user == @item.user %>
		<%= link_to 'Edit listing', {:controller => 'items', :action => 'edit', :id => @item}, :id => "edit_button", :class => "btn btn-primary" %>
	<% end %>
	<div class="row">
		<div class="col-md-12 listing_title">
			<h2><%= @item.name %></h2>
		</div>
	</div>
	<div id="listing_body" class="row">
		<div id="listing_body_inner" class="col-sm-12">
			<%= link_to @item.image.url(:original), :class => "zoom" do %>
				<%= image_tag(@item.image.url(:resized), :class => "listing_img", :alt => "Small image") if @item.image? %>
			<% end %>
			<%= @item.description %><br>
		</div>
	</div>
	<table id="listing_table" class="table">
		<tbody>
			<tr>
				<td><b>Location:</b>
				<% if current_user.present? %>
					<%= @item.location %></td>
				<% else %>
					<% location = @item.location.try(:split, '') || 'something'.split('') %>
					<% location.map! {|c| "█"} %>
					<%= location.join %>
				<% end %>
				<td><b>Posted: </b><%= time_ago_in_words(@item.created_at).gsub('about','') %> ago</td>
				<td><b>Price:</b>
					<% if @item.price == 0 %>
						Free
					<% else %>
						<%= number_to_currency(@item.price) %>
					<% end %>
				</td>
			</tr>
		</tbody>
	</table>

	<div class="row">
		<% if current_user.present? && @item.user_id == @coop.id %>
		<div class="col-sm-12">
			<b>This item is available at The Coop. The Coop is located at the bottom of Jackson Hall, facing LSC.</b>
		</div>
		<% elsif current_user.present? %>
			<div class="col-sm-12">
				For more information, contact <b><%= @seller.email %></b>
			</div>
		<% else %>
			<div id="register_account_button_wrapper">
			<%= link_to 'Register a free account to contact this seller', new_user_registration_path, :id => "register_account_button", :class => "btn btn-lg btn-primary btn-block" %>
			<% end %>
			</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <style type='text/css'>@import url('http://getbarometer.s3.amazonaws.com/assets/barometer/css/barometer.css');</style>
  <title>Trinlist</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<script type="text/javascript" charset="utf-8">
  BAROMETER.load('tqAc5xDbka7NK3kLm94fT');
</script>

<body>

<div id="navbar" class="navbar navbar-default navbar-static-top center">
  <div id="navbar_container" class="container-fluid">
    <div class="navbar-header">
      <button id="navbar_button" type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Trinlist', root_path, :class => "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="nav_link <%= 'active' if (request.env['PATH_INFO'] == '/') || params[:category] == 'books' %>"><a href="/categories/books">Books</a></li>
        <li class="nav_link <%= 'active' if params[:category] == 'furniture' %>"><a href="/categories/furniture">Furniture</a></li>
        <li class="nav_link <%= 'active' if params[:category] == 'electronics' %>"><a href="/categories/electronics">Electronics</a></li>
        <li class="nav_link <%= 'active' if params[:category] == 'clothes' %>"><a href="/categories/clothes">Clothes</a></li>
        <li class="nav_link <%= 'active' if params[:category] == 'misc' %>"><a href="/categories/misc">Misc.</a></li>
        <li class="nav_link <%= 'active' if params[:category] == 'free' %>"><a href="/categories/free">Free</a></li>
        <li class="nav_link <%= 'active' if (request.env['PATH_INFO'] == '/items') %>"><%= link_to 'All', root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li id="nav_add_item"><%= link_to 'Add Listing', new_item_path %></li>
        <% if current_user.present? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
          <ul class="dropdown-menu nav-pills nav-stacked">
            <li>
              <a href="/listings">
                <% unless Item.where(user_id: current_user).count == 0 %>
                  <span id="listings_count" class="badge pull-right">
                  <%= Item.where(user_id: current_user).count %>
                  </span>
                <% end %>
                My Listings
              </a>
            </li>
            <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
            <li>            
              <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
              <%# user is not logged in, show signup and login links %>
            </li>
          </ul>
        </li>
        <% else %>
          <li class="nav_link"><%= link_to 'Register', new_user_registration_path %></li>
          <li class="nav_link"><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container">
  <% if notice %><div class="alert alert-info"><b><%= notice %></b></div><% end %>
  <% if alert %><div class="alert alert-danger"><b><%= alert %></b></div><% end %>
  <%= yield %>
</div>

<% if Rails.env.production? %><%= render :partial => 'shared/ga' %><% end %>

</body>
</html>

app/views/pages/index.html.erb
<h2>trinlist</h2>
<%= link_to 'view list', items_path %> <br>
<%= link_to 'post an item!', new_item_path %>

app/views/shared/_ga.html.erb
<script type="text/javascript">
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-44417186-1', 'trinlist.com');
	ga('send', 'pageview');
</script>